### ISSUE TITLE
Is there a way to refresh the legend when a definition expression is set?

### ISSUE THREAD

**Issue by jmrroy** [Esri/angular-esri-map#178]
Hi,
I'm wondering if there is a way to refesh the legend after setting a definition expression. The legend works well on layer visible event, but when we set a definition expression the legend is unchange. For example in your legend example page, if I set the water bodies to "Lake", the other water bodies still visible in the legend.
In ArcgisOnline when a filter is set, the legend don't refresh and we need to re-symbolize the layer that the legend make change.
I'm starting to split all my features layer, but it will much more easier to work with just few features layer that I can filter.

**Comment by jwasil** [comment]
Hi @jmrroy that is a good question.  I can also re-create the condition where I have a feature layer with a definition expression, but the [esri/dijit/Legend](https://developers.arcgis.com/javascript/jsapi/legend-amd.html) that you refer to does not show _only_ those filtered categories.  @tomwayson, am I correct in my assumption that this just isn't how this dijit currently works, and rather its focus is on the currently visible layers on the map?

**Comment by tomwayson** [comment]
I don't know off hand what the expected behavior of the Legend dijit is w/ a definition expression. If you can get the legend to update by setting a definition expression [in the sandbox](http://developers.arcgis.com/javascript/sandbox/sandbox.html?sample=widget_legend), then we should be able to do it in this repo. If not, then that is not functionality that we will support here.

**Comment by jwasil** [comment]
@jmrroy while investigating this, I'm thinking more and more that the Legend dijit doesn't support this behavior.  I'll go ahead and close this, but we can revisit if any of us come across something new later.
