### ISSUE TITLE
New patterns page for loading a map in a route's resolve

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#232]
Now that maps and layers have been decoupled from the UI (views), we can actually load them in a route's resolve.

**Comment by jwasilgeo** [comment]
@tomwayson over in #289 @sicollins is using the Angular 1.5.6 `ngComponentRouter` and **angular-esri-map** lazy loading.  Looks like the timing is good to create this new Patterns page, and I'm thinking at least with `ngRoute` for now.  Any other thoughts?

**Comment by djrpascu** [comment]
I have an Angular Ionic app in which I'd like to preload the map object before I hit the view/directive, maybe on app run. App starts on the home page but I have a menu item to list graphics data retrieved from the feature layer of a map object. The graphics data isn't there until the map view and feature layer is loaded. Is there a way to preload the map so that it's available up front? I think my objective is related to this issue. If I hit the menu item to load the map view first then hit the menu item to list the graphics data, it works fine. Doesn't work if I don't hit the map menu item.

**Comment by andygup** [comment]
@djrpascu take a look at the patterns and samples in this [repo](https://github.com/jwasilgeo/ionic-esri-map). Ionic has its own life-cycle that has to be taken into account.

**Comment by djrpascu** [comment]
@andygup thanks for the reply! I did use that repo as a basis, and have had some contact with jwasilgeo who's been extremely helpful! Can you point me specifically to the example that loads the map up front? I can't seem to find it. I've been using a mix of the onload and registry patterns. Here's my project:
[EVChargeStations](https://github.com/djrpascu/EVChargeStations)

**Comment by andygup** [comment]
Ahhh, gotcha. Have you considered using a Feature Layer Query to get the graphics back without a map? This way you can logically de-couple the map from the features and graphics. [Example](https://developers.arcgis.com/javascript/3/jssamples/query_nomap.html).

There isn't a sample that shows how to lazy-load a map because it's not possible with Ionic or Cordova. So, below is a little insight into why it's not possible.

Ionic uses a native-mobile pattern to UI development that is view-based, and there can be multiple, logically separate views. This is significantly different from the common responsive-design approach to web apps which essentially contains a single, dynamic view.  With a view-based implementation pattern, Views cannot be pre-loaded because they either don't exist in the layout and are `undefined`, or they have been stubbed in an uninflated state with a height of zero and width of zero. A map with no height or width will have no Extent and therefore it can't be populated with tiles.

Essentially each view has to have primary focus in order for it to inflate correctly. When a view is in focus, all UI components can then honor layout definitions, screen height, width and orientation, available memory, and then draw and populate layout elements, etc.

**Comment by tomwayson** [comment]
Looks like you're using UI router? Can you use it's [resolve parameter](https://github.com/angular-ui/ui-router/wiki#resolve) to pre-fetch "the map"? If needed to be called from a different route, you should be able to have your mapService fetch the map info and later have your map route's resolve or controller get that map info from the service.  That's what you would do if in a non-ionic app, but I have no idea if/how that works in ionic.

That said keep in mind, that w/ a 3.x map, there are a few parts that need to be fetched async:
1) the features
2) the basemap(s)
3) possibly the code modules themselves (if you're using any that are not included in the CDN build of the API)

So you may need to wrap your code in calls to `esriLoader.require`

**Comment by djrpascu** [comment]
@andygup thanks for the detailed explanation! I should take a step back and say that I'm new to Angular, Ionic, Esri, so what I wrote I don't even know if that's the right way to do things. I did what I could to make things work. I'd be very interested in your comments on what I could do to improve it. Perhaps change it to a single view?

@tomwayson thanks for the reply! I saw that but I'm not sure what I can call or create on the controller/service to initialize the map since the map is loaded via the directive in the template, I think. I suppose I could try newing up a map in the controller using esriLoader?

**Comment by andygup** [comment]
@djrpascu The Ionic multi-page architecture you have looks okay to me. You can use either a single page or a multi-page app structure. Here's a [good overview](http://www.gajotres.net/ionic-framework-tutorial-2-anathomy-of-a-page/).  Both have their strengths and weaknesses. If anything comes up with the Ionic architecture feel free to drop us a line over at the other repo.

**Comment by tomwayson** [comment]
Closing as this repo is in maintenance mode.
