### ISSUE TITLE
No map content rendered

### ISSUE THREAD

**Issue by sicollins** [Esri/angular-esri-map#289]
I'm using the latest angular-esri-map with esri 2 api and css in my Angular 1.5.6/7 (with new Component Router) app.

Just cannot get the map to render.

I can see the 'esri-map-view' element does get content but never gets any svg content.

I can see api call to:
https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer?f=json

I created a totally stripped out vanilla angular app using your examples and they do work, I can see a map.

In addition to the call above, the working version I can see also calls:
http://static.arcgis.com/attribution/World_Topo_Map?f=json

So something is conflicting but I cannot see what and don't get any errors.

Here's a plunkr I've put together. Click the Map menu item.
https://plnkr.co/kJbdW3DLNhnLDSKGXy1i

Any help much appreciated

Sorry should have said I'm using lazy loading as per this example 
http://esri.github.io/angular-esri-map/deferred-map.html

**Comment by jwasilgeo** [comment]
Hi @sicollins, please see #286 for a similar situation.  It turns out that your Esri JSAPI v4 `MapView` is indeed there, but the `%` height you assigned in your css isn't currently working.  To get it to show up, try something like:

```css
.esri-view {
    padding: 0;
    margin: 0;
    height: 400px; /*pixels here, as an example instead of percentage*/
    width: 100%;
}
```

This resides as a child of `<esri-map-view...>` in the DOM.  For your project you may want to try out different combinations of absolute and relative height units for those two nodes.

**Comment by sicollins** [comment]
Thank you very much @jwasilgeo - can't believe it was that.

I've tweaked in my actual app and got it render (and in that plunkr I set up).

My app is using bootstrap 3 which seems to be causing lots of styling issues with the % height/width dimensions. Would love to hear from anyone who has figured and good solution to avoid bootstrap conflicting but also keeping the app fully responsive?

Any ideas why now in my plunkr example, setting zoom:17 programatically isn't zooming and centering using my lat/long but works if I use view-options?

**Comment by jwasilgeo** [comment]
@sicollins regarding your last question, that's because those properties are not part of the [`"esri/Map"`](https://developers.arcgis.com/javascript/latest/api-reference/esri-Map.html).  If you have had experience with Esri JSAPI 3.x, then that is one of the major things that have changed now with Esri JSAPI 4.x.  The [`<esri-map-view>` directive](http://esri.github.io/angular-esri-map/docs/#/api/esri.map.directive:esriMapView) we provide in this library takes the properties of [`"esri/views/MapView"`](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html).

**Comment by jwasilgeo** [comment]
In fact, I'll add a couple more links in this library's API docs that more clearly point this out. :smile:

**Comment by jwasilgeo** [comment]
As for Bootstrap, @sicollins, we've had chances to use Bootstrap, [Esri's Calcite Bootstrap](https://github.com/Esri/calcite-bootstrap), [Angular UI Bootstrap](https://angular-ui.github.io/bootstrap/), and even Material Design among different projects.  From what I'm familiar with, I think you may have to dive in and also supplement whatever you end up using with additional CSS of your own.

**Comment by sicollins** [comment]
thanks for your help on all this @jwasilgeo much appreciated. Closing ticket....

**Comment by gcmestre** [comment]
I also had this problem. Thank you.

**Comment by gcmestre** [comment]
@jwasilgeo Thank you for you post it was realy helpfull. 

I'm using angularJs, do you have any hint on how can I change the height value so that the map will adapt to the screen size?

**Comment by jwasilgeo** [comment]
^ cc @andygup

**Comment by andygup** [comment]
@gcmestre Since I'm not sure how you've built your app, the best example I can provide is one that I know works. Here's an Angular 2 + Ionic prototype app and the map CSS is defined in `index.html` as show [here](https://github.com/andygup/ionic2-esri-map/blob/master/index.html#L42-L47).

And, the map `<div>` in that example lives in [`home.html`](https://github.com/andygup/ionic2-esri-map/blob/master/pages/home/home.html#L23).
