### ISSUE TITLE
Add Layers to ESRI MAP

### ISSUE THREAD

**Issue by benitazz** [Esri/angular-esri-map#309]
How do we add layers to the ESRI MAP using Angular 2, I have layers that I would like to add to the ESRI base map

**Comment by jwasilgeo** [comment]
@benitazz have you read over these notes about Angular2 in the readme?  https://github.com/Esri/angular-esri-map#what-about-angular-2

This library is for Angular1.  With Angular2 in general, once you have established which module loader you will use (e.g. SystemJS, Webpack), you can then follow Esri JSAPI documented conventions within Angular2 components.  The links within the readme section about Angular2 have more info and working examples of layers being added to maps.

**Comment by benitazz** [comment]
Thank you

**Comment by jwasilgeo** [comment]
Great, then in that case you can continue to write additional code for the map in your own Angular 2 map service in order to add layers according to documented Esri JSAPI methods.

If using JSAPI v3.x: https://developers.arcgis.com/javascript/3/jsapi/map-amd.html#addlayer
If using JSAPI v4.x: https://developers.arcgis.com/javascript/latest/api-reference/esri-Map.html#add

**Comment by benitazz** [comment]
You are a star

**Comment by BartSu** [comment]
How about add map layer in vue.js framework. There seems no related repo in Esri.

**Comment by jwasilgeo** [comment]
@BartSu please visit https://github.com/esri/esri-loader.

**Comment by tomwayson** [comment]
@BartSu https://github.com/esri/esri-loader#vuejs
