### ISSUE TITLE
Popup Action Item Out of Place

### ISSUE THREAD

**Issue by djrpascu** [Esri/angular-esri-map#325]
#### Expected behavior

- Some items in popup actions are out of place.

#### Actual behavior

- In sample, "Directions" action seems out of place on some features.

#### Steps to reproduce the behavior

1. See plunk here - https://plnkr.co/edit/y5eoSB8tT6KE79u5gIRa?p=preview
2. From a high level, select a collection of features so you can page through the popup widget to view different features.
3. In some features, the "Directions" button/label is out of place.

**Comment by jwasilgeo** [comment]
@djrpascu I'm having trouble recreating the issue in your example.  Is this something that can be isolated to the JSAPI alone without angular-esri-map, or something specific with css?  That is, could it be recreated in one of these samples w/o this library?

https://developers.arcgis.com/javascript/latest/sample-code/popup-custom-action/index.html

https://developers.arcgis.com/javascript/latest/sample-code/popup-actions/index.html


thanks

**Comment by djrpascu** [comment]
@jwasilgeo thanks for the response and sorry for the late reply.

I modified the plunk to zoom to an example of a problem popup. Look for the blue icon nearby, has a title of "Neal Blaisdell Center Parking Structure". I could not reproduce in the JSAPI examples. 

Here's also a picture of what I'm observing:
![problem_popup](https://cloud.githubusercontent.com/assets/14353513/23186443/46a1ceba-f82b-11e6-873b-05aa19fd43e9.png)

Notice the "Directions" text is out of place.

**Comment by jwasilgeo** [comment]
@djrpascu it looks like ionic css is interfering and adding a margin of 20px on all sides to the span for the icon, which makes your "Directions" text appear to be higher up with the overall flex positioning.

This rule is messing things up ionic.min.css:

```css
.card,.list-inset {
    overflow: hidden;
    margin: 20px 10px;
    border-radius: 2px;
    background-color: #fff;
}
```
Can you override it in your custom styles?

Unfortunately, this is happening because the word "card" is present in that icon's span `class` property, which I think may be a bug with the JSAPI.  If you inspect the DOM for that action icon span, you'll see that a there is some invalid html being placed inside that `class` property from the "Notes" attribute for this feature.  I will follow up with the JSAPI team with what we've found here.

I'll close this for now since it isn't something this library can do much about, but please let me know if you have any other thoughts or concerns.

**Comment by djrpascu** [comment]
Oh my goodness... I've compared that code with a good popup so many times and didn't realize the class had the HTML in it. Didn't look at styles beyond esri-popup__icon esri-popup__action-image. Need to learn to make better use of Chrome tools.. Thank you so much!

**Comment by jwasilgeo** [comment]
👍
