### ISSUE TITLE
Changelog links don't work

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#81]
https://github.com/Esri/angular-esri-map/commit/080f5a077f00a567d715ea90af60ca4ad9fcdca1#commitcomment-13133513

**Comment by tomwayson** [comment]
Sill broken

**Comment by jwasil** [comment]
Is there anything that would preclude us from using the style for the links found in [an earlier version](https://github.com/Esri/angular-esri-map/commit/080f5a077f00a567d715ea90af60ca4ad9fcdca1#diff-4ac32a78649ca5bdd8e0ba38b7006a1eL20)?  That is, only `[link text]` instead of `[link text](url)`?  I thought that may have been working before.

**Comment by tomwayson** [comment]
No, that's my plan.

**Comment by tomwayson** [comment]
resolved in ba54699fd00e9bc05bb203e429d6ab446a1c77b0

**Comment by jwasil** [comment]
:+1: !!
